### ISSUE TITLE
Gzipped xml tapes are not loading correctly

### ISSUE THREAD

**Issue by gsaqui** [betamaxteam/betamax#135]
```
!tape
name: All Areas
interactions:
- recorded: 2013-04-16T04:31:23.166Z
  request:
    method: GET
    uri: http://someurl.com
    headers:
      Accept: '*/*'
      Accept-Encoding: gzip,deflate
      Host: webpull.globalsportsmedia.com
      Proxy-Connection: Keep-Alive
  response:
    status: 200
    headers:
      Content-Encoding: gzip
      Content-Type: text/xml; charset=utf-8
      Date: Tue, 16 Apr 2013 04:31:19 GMT
      Last-Modified: Tue, 16 Apr 2013 02:23:37 GMT
      Server: Apache/2.2.3 (Red Hat)
      Vary: Accept-Encoding
      X-IP: 10.3.230.14
      X-Server-Name: (null)
    body: !!binary |-
      H4sIAAAAAAAAA4VbW3PiOBZ+n1/hylbtPvV07NynL1PGGEMwhsaGbPIyJUAD6hiLke2kk1+/ckgkcs5x9mW6q8dfJJ3rdz4pX//8tc2dB65KIYtvR+7vx0d/fv/t67rcqtL+s6f/2Sl3UlXfjkq5XHJ15OSsWH874kXzt7L6a80LrljFV/rrY/fk0/HpJ/fcOT79wzv54+Ti6PvXLa82cuXs//hL6O/cI6dgW/7taM2rv5jirNSf7ZjS/1Zx9fr/mn/XXx85DyyveQP6jD9q9mK+0FvSn3zeL/T9a/MDnNef8rLmUtZFpZ6WcqU/ftvCjVT56gh+7bV87ZeCoY8vwcd+LzLf/73esEKUFXvZG9jSFQTOUgOsy0qxXK+GYN4JgHX60zdYh20UE8Ra3ikE+YkFFeucrXi5wbgTaLdOf2Zwm5o8l/Y6wEwtRtUFF06XqbosWc62GH4Klwz80Rs8YNuFXFFWOYXGDPrmgMFGFMyZTDHq7Bigskl4iOIldzImdlxg7CU0aTQz+4xq6mRX8GT9oYmUvizWzlD/h4DBhQZJ9w02KEhrXJ1BSDc5gEh9MBJ2DmFTC1OUr6+grwfTHweIf4ioP4bJdT0xi1yzHZkpxzDmr8cm5q+lWtEgeJrJdPgGGsrm2y4VE+4xPNPQLrbHTfmuXuRiSYFhNRjObgy4fmSiokAweIfRnQE9qfXTc0sFcWH8xv74DRgzWVIQaP540DEQvmCFJBeCOxz5wRtqxJZMEhhUqEZ+ajE5eyJj0EWlatSdH8BW4oFT50KVahTFBqbzSpLF1D2BmTK69Q3siRVbpigUDJEknLyhEr5jOYE5hZjxyKw03pLuPYXBNPFNBE/YfVtfQbVw4scWlvOy0pWNwJ1By0/6A4PbiFzsdk1JpJBwoz/87A35g1WkDc/hasPU2CNl9Uo4vmIL0mkXMOzTgSkhqSjWTDMW6oAX0AXp1BwwVcKJWXFPrXcJK0l6aypC+qTIPV5CJ2TXxncZ+ylavYe6RNY3dsk2TGjOs6Jg8GzZ0LSjrFb3W97GQzxUkWe+6YKzQmhu9+IKJ9yKhukRAeAdwzSa3ZmqMnte8LbTeqhezgdm7bngVUE1Ug/VvdvQHPaWbzm1kgftGtoYzcRWqk+xzgwibLwziExGJmwSzY03XBXOiOk40DRjUDYOerHR5+ZHIHbURi3/VmKJySU6qR9bdpmvOR18cBE/saCmFFK0EsZrJ7QMUccORfQQqRwbi3ZkVT5qexAotFDPxHdHB2rD1XqsJDrKKbRFpzs4QNaaCxEgGNzByOSuppNcSarhncKjBZO5Re24M+dqxQ+dDfCwYgSZOWTAi4bbO3uPFx+wCdQyAlsKgg0jysAZOm1kCEHQdEECAoMlGHffQZwuwZLOoS+CgTXQv//1q3f6peLO6j+DBymoWnwON9q9Nr7s/hQLWVeEM8+hWcPo9g0Vrp92BLk6h+EW/jC5EP5Ts0rqFMqdqNatjYhW1GpC2zJCJSpFguDhwqxvQNVGyB2Vtag7Rb6poRFbUGF6AatnZGelSM9K1DKXsJpFNqiiDZmyqP9FM2OENsNdotMknfeYTx2hZ8Ca4sOwmwxtLRry4okqeajmxaFhm7qwy2pDcVQX5nncMdUhFouW8urC/cWd2wMUuT/Ufka+SbMRW7E1K5ckT/JgMI1uBhaYs0ciT1wP0dr4EERCoMNGWWIhtY51VtCEHQbhaDp4DxQ1ydjxfGBsP5JKLpeUx1DTGY3vLOq5Cfp/aor8ncAgTmyuJGwraKp5CjeZDEz5SITuvxQGbjGJ/HcYcqVzGCDTG4Oa6la6IkGImdpMSXnB1+Qocg49loa3FvW03PA8J3k+KqZpbNhaKrhSzIm5JIeLC2iUdGzMn8otrXW5FzCOpwdDgu4Rm9cuShFwaM90ZhIurWnJ4BJ6O70xwZU+suc28o2KXZqZeTDV3TA8+SKdTG6bv159cbgzUc1fu1+KpdhR1rpCwpTV6zJWPLek4hWsFdnYRGsmqe7vIqkom9mVaj0zkBrkMdzfzIb4bE0Hq+dCj9zZDLxr6VYe0ivuBhYktgu2eKQ4uwc3eGcNeKcNKBZUsfWQZjENjXY55docVBf2TjDHPGBderSglBjvDEsPma2bT7KihxGU8Wn3fUaY4CbnD5iGpjB9Dhxf02FyCIEgf2C8reeJWuTURIG6pJ8dTCGVWNf642LldJha1GR1Q8p6x2hpvqoXVLhAT3T6hgV02IZtGekJJFh3LEgt2Ir0H9xdJza1osNz8Ux47wRNMCMrjXO1Jc2AGldnbseepruWG2cu1FoUH8wjiOTbdAg056PWPYVmCW4PhPinLftgPRTbgeUEgSwr5kzJqn2GJp6ZcUVAevwcnqxrZbWu3IqCXAeJT13bjd5QH01m56jgx2b8CXMnZfmDjhqiwqAOE01N+kaK0564hNaMssOrhorr9knB0HQwu7WwJ5rqww7fz4zj+kxQQxnqVX17P9GXxapWVNK5x7AbXNtucK0Tle7qSKYYhf81RZP/EjRnRBQ6PWCaRVU2zIUS5pFWEcyseKDP1TTxiy+k+o10h2RgFPNEn00xXf+oogmtObGZOtEu25IgGI4Tm26TmqtKNvlGbRNNkOnQEsjqd2coqqp8KdMJfxCUHy8QJ8ziw58Q10taIEUi7jw6xM1FseRF9bJ2teHOPjtaBOhLaO3UOirVI0jzN4r8wDKQZaZxZxolVmz1soFMLhhNn6D9ssCqtbW639su0NEsy/Zy6V5BI85SU09m6f8t7x66IJtZnvwq4aZVi3aLBr+oGx9UlxXPZU2RVA91wHRkCEzKhPbdiKmKvI7GaZyZe8M9iJ7iPNRBU1vu0/2SGk4KwOiGqBeZ5tvTwbXcNCoQWRW9MxTklhe+LBvWuqnRg66HtLLO2EqrsmCvAhlJ12DlB8NPG2GDlMGfWuql1jqtBCnNIvY0ju1Gc/FAJTK6QetMrZ6rmpmJoBYwcoK+WSjYiJzwPBLhA7u3QOaSHh/O4ebCwPgtXNZ0j3aRijqZ3toa/FK5nygYTMJJaIrQhCtC6fKOYQGa2ZVmqqYX8tAN9dxO/XM99T/XfM8HyJCCsfGGHC/5y1iJ5S4YTKlp1K8BWGjGs5UUn0M6+nhovSbv20sa0gt6ViDuiZ+UgoXuB5LAhEjCH3UVzvlK0pMzenWS3L3D3nHWMvujwJzYy5YJ2+khp8G3yaQuEsJvrHVbjOpeIJki7tjCoHNBftArXEQLM9+o0xnbkBzPvYJLZraGZbJYkyIBjLT5zPSHOSs0caVSAsmC2dx4Iqubt15UfYZWHA7smw2h9LRPncpDvCkZmPKQiFrTO9c9+UIBoQ0T3wJZTeY6EvjeX8vvlXAyY+EuTQWrldSdGRFymK82Ovx80abiQpAl8X6hy6QiAxG1GVsZVHPjTIYFBNmoeHn2RstAEHRnhEf/mesZXfwk75fR7Bzbx3K6SCqyYaMHbGF8AFqLmriTRmHbGZis6shSm+JTn6tnvpYPdO9FckJkd1rna0baBalB/am9hlNSRz0FQt331qiVwdOOtAkiQIF1QPDMNXf6YFiGzusmpgl0efPE5p4AwU2GtqyGzYNFqhhfoDv+1MRWWFZ07UfVtDc1Q0CPKfnBNS+Sp3v2IUpPFC2bhD7rWcLUU0xPPQQGmj8KzR4jLvV0QM3yMNO6lrRGXG1ZQZALNElFUzO36hGMU7tDsnPfasj9WjcHRSyEOsogNVk2WHLadmjcGkwtSL2APghENGUNrA4wKBXj1GUJkroH9ip/ULGcYoKI1g19+6CPPbP7TduDPhjA8dwsFrOKJOAuYvuxfUMTC52beh4qK04NYi4q4XE2s9hqU7e0C6TNxjOjw8T1L75dyFoRj1ldVP5Hw4N70OWeoDm9W+plJqrmo/hAMc8raqNoYBz1D94F5iv5QKJQf4/NLhPevPhpY1dINU0sEzGPhV5DlYKjW8rxIfyRHjzgmhM7G01kG2/Fz2MzC1JVTd8dokYwHdsbErltCRc0Ak/tW/dpXdIvQZG0m9qnOynbP7kqKFEGTX1pYKplupRVi0WwqBtYRUpzDLG/r2gUw+ZqVZF6Grp1nJtel+Y62O7pe06kX82TQxhNpVzUSsLU3jvuyN8EcNG79fTG3uE+8hWlnbhIgQ76ByBRPe8Tghoc4BYzq8w1AhknB1xoxdnQgGb3za84UNoQekZ9Ywn2DSNvtD302ji1M/ve5xQI3dwloa0p7dHhoQIW2cfXkViopoZR15JIY7m2u7zmqiSNiO6NBvaOQzMa7si/dQqRvyyC3qNbNXIoS/lAnQ0J15F9SqOJA6uc5rKK/u0UpJyMbMJqgzJKuvaQthBFB9cbusy+muV1pHr74+VXnL7/9j84oRBsATUAAA==

```
